#!/bin/sh

#   basic image handling scripts
#
#   Mark Jenkinson
#   FMRIB Image Analysis Group
#
#   Copyright (C) 1999-2012 University of Oxford
#
#   Part of FSL - FMRIB's Software Library
#   http://www.fmrib.ox.ac.uk/fsl
#   fsl@fmrib.ox.ac.uk
#   
#   Developed at FMRIB (Oxford Centre for Functional Magnetic Resonance
#   Imaging of the Brain), Department of Clinical Neurology, Oxford
#   University, Oxford, UK
#   
#   
#   LICENCE
#   
#   FMRIB Software Library, Release 5.0 (c) 2012, The University of
#   Oxford (the "Software")
#   
#   The Software remains the property of the University of Oxford ("the
#   University").
#   
#   The Software is distributed "AS IS" under this Licence solely for
#   non-commercial use in the hope that it will be useful, but in order
#   that the University as a charitable foundation protects its assets for
#   the benefit of its educational and research purposes, the University
#   makes clear that no condition is made or to be implied, nor is any
#   warranty given or to be implied, as to the accuracy of the Software,
#   or that it will be suitable for any particular purpose or for use
#   under any specific conditions. Furthermore, the University disclaims
#   all responsibility for the use which is made of the Software. It
#   further disclaims any liability for the outcomes arising from using
#   the Software.
#   
#   The Licensee agrees to indemnify the University and hold the
#   University harmless from and against any and all claims, damages and
#   liabilities asserted by third parties (including claims for
#   negligence) which arise directly or indirectly from the use of the
#   Software or the sale of any products based on the Software.
#   
#   No part of the Software may be reproduced, modified, transmitted or
#   transferred in any form or by any means, electronic or mechanical,
#   without the express permission of the University. The permission of
#   the University is not required if the said reproduction, modification,
#   transmission or transference is done without financial return, the
#   conditions of this Licence are imposed upon the receiver of the
#   product, and all original and amended source code is included in any
#   transmitted product. You may be held legally responsible for any
#   copyright infringement that is caused or encouraged by your failure to
#   abide by these terms and conditions.
#   
#   You are not permitted under this Licence to use this Software
#   commercially. Use for which any financial return is received shall be
#   defined as commercial use, and includes (1) integration of all or part
#   of the source code or the Software into a product for sale or license
#   by or on behalf of Licensee to third parties or (2) use of the
#   Software or any derivative of it for research with the final aim of
#   developing software products for sale or license to a third party or
#   (3) use of the Software or any derivative of it for research with the
#   final aim of developing non-software products for sale or license to a
#   third party, or (4) use of the Software to provide any service to an
#   external organisation for which payment is received. If you are
#   interested in using the Software commercially, please contact Isis
#   Innovation Limited ("Isis"), the technology transfer company of the
#   University, to negotiate a licence. Contact details are:
#   innovation@isis.ox.ac.uk quoting reference DE/9564.
export LC_ALL=C


Usage() {
    echo ""
    echo "Usage: `basename $0` <image> <keyword> <value>"
    echo ""
    exit 1
}

if [ $# -lt 3 ] ; then 
    Usage
    exit 0;
fi

if [ _$FSLDIR = _ ] ; then
    FSLDIR=/usr/local/fsl
    export FSLDIR
fi

imfile=$1
keyword=$2
value=$3

if [ $keyword = dim1 ] ; then keyword=nx; fi
if [ $keyword = dim2 ] ; then keyword=ny; fi
if [ $keyword = dim3 ] ; then keyword=nz; fi
if [ $keyword = dim4 ] ; then keyword=nt; fi
if [ $keyword = pixdim1 ] ; then keyword=dx; fi
if [ $keyword = pixdim2 ] ; then keyword=dy; fi
if [ $keyword = pixdim3 ] ; then keyword=dz; fi
if [ $keyword = pixdim4 ] ; then keyword=dt; fi

tmpbase=`${FSLDIR}/bin/tmpnam`;

# generate the xml-style header with fslhd
${FSLDIR}/bin/fslhd -x $imfile > ${tmpbase}
# exit if the above didn't generate a decent file
if [ `cat ${tmpbase} | wc -l` -le 1 ] ; then
  exit 0;
fi

# modify header, reprocess and pass onto fslcreatehd
if [ `cat ${tmpbase} | grep "^[ 	]*$keyword[ 	]*=[ 	]*" | wc -l` = 0 ] ; then
    # this keyword is not in the fslhd output so add it
    cat ${tmpbase} | grep -v '/>' > ${tmpbase}2
    echo "  $keyword = \'$value\'" >> ${tmpbase}2
    echo "/>" >> ${tmpbase}2
else
    # the keyword is present so change its value
    cat ${tmpbase} | sed "s/^[ 	]*$keyword[ 	]*=.*/  $keyword = \'$value\'/" > ${tmpbase}2
fi

${FSLDIR}/bin/fslcreatehd ${tmpbase}2 $imfile

/bin/rm ${tmpbase} ${tmpbase}2

