#!/bin/sh

#   POSSUM
#
#   Ivana Drobnjak & Mark Jenkinson, FMRIB Analysis Group
#
#   Copyright (C) 2005-2007 University of Oxford
#
#   Part of FSL - FMRIB's Software Library
#   http://www.fmrib.ox.ac.uk/fsl
#   fsl@fmrib.ox.ac.uk
#   
#   Developed at FMRIB (Oxford Centre for Functional Magnetic Resonance
#   Imaging of the Brain), Department of Clinical Neurology, Oxford
#   University, Oxford, UK
#   
#   
#   LICENCE
#   
#   FMRIB Software Library, Release 5.0 (c) 2012, The University of
#   Oxford (the "Software")
#   
#   The Software remains the property of the University of Oxford ("the
#   University").
#   
#   The Software is distributed "AS IS" under this Licence solely for
#   non-commercial use in the hope that it will be useful, but in order
#   that the University as a charitable foundation protects its assets for
#   the benefit of its educational and research purposes, the University
#   makes clear that no condition is made or to be implied, nor is any
#   warranty given or to be implied, as to the accuracy of the Software,
#   or that it will be suitable for any particular purpose or for use
#   under any specific conditions. Furthermore, the University disclaims
#   all responsibility for the use which is made of the Software. It
#   further disclaims any liability for the outcomes arising from using
#   the Software.
#   
#   The Licensee agrees to indemnify the University and hold the
#   University harmless from and against any and all claims, damages and
#   liabilities asserted by third parties (including claims for
#   negligence) which arise directly or indirectly from the use of the
#   Software or the sale of any products based on the Software.
#   
#   No part of the Software may be reproduced, modified, transmitted or
#   transferred in any form or by any means, electronic or mechanical,
#   without the express permission of the University. The permission of
#   the University is not required if the said reproduction, modification,
#   transmission or transference is done without financial return, the
#   conditions of this Licence are imposed upon the receiver of the
#   product, and all original and amended source code is included in any
#   transmitted product. You may be held legally responsible for any
#   copyright infringement that is caused or encouraged by your failure to
#   abide by these terms and conditions.
#   
#   You are not permitted under this Licence to use this Software
#   commercially. Use for which any financial return is received shall be
#   defined as commercial use, and includes (1) integration of all or part
#   of the source code or the Software into a product for sale or license
#   by or on behalf of Licensee to third parties or (2) use of the
#   Software or any derivative of it for research with the final aim of
#   developing software products for sale or license to a third party or
#   (3) use of the Software or any derivative of it for research with the
#   final aim of developing non-software products for sale or license to a
#   third party, or (4) use of the Software to provide any service to an
#   external organisation for which payment is received. If you are
#   interested in using the Software commercially, please contact Isis
#   Innovation Limited ("Isis"), the technology transfer company of the
#   University, to negotiate a licence. Contact details are:
#   innovation@isis.ox.ac.uk quoting reference DE/9564.
export LC_ALL=C

Usage() {
    echo "./generate_pulse <brain> <subjdir> "
    echo ""
    echo "Copy this file from its location to your working dir"
    echo "use ti as gui"
exit 1
}
[ "$1" = "" ] && Usage

brain=$1
subjdir=$2

seq=epi         #      def=epi
TE=0.030       #(s),  def=0.03        
TR=3    #(s),  def=3  
TRslc=0.12  #(s),  def=0.12 =  TR/numslc for epi
                 #               =  TRline for ge 

readdir=x+          # it always has to be plus
Nread=64            #      def=64  -- Nread 
phasedir=y+         # it always has to be plus   
Nphase=64            #      def=64  -- Nphase
dread=0.004         #(m),  def=0.004 = FOV/Nread
dphase=0.004         #(m),  def=0.004 = FOV/Nphase

slcthk=0.002     #(m),  def=0.006 

numvol=2     #      def=1                                  
numslc=2     #      def=1                             
  
zstart=0.03     #(m),  def=0
slcdir=z+
gap=0            #(m),  def=0  
maxG=0.055       #(T/m),def=0.055
riseT=0.00022    #(s),  def=0.00022
BW=100000        #(Hz), def=100000=100KHz                               
cover=100        #(%),  def=100
angle=90         #(deg),def=90 

#POSSUMDIR=~ivana/fsldev/${FSLMACHTYPE}/bin

${POSSUMDIR}/pulse -i $brain -o pulse --te=${TE} --tr=${TR} --trslc=${TRslc} --nx=${Nread} --ny=${Nphase} --dx=${dread} --dy=${dphase} --maxG=${maxG} --riset=${riseT} --bw=${BW} --numvol=${numvol} --numslc=${numslc} --slcthk=${slcthk} --zstart=${zstart} --seq=${seq} --slcdir=${slcdir} --readdir=${readdir} --phasedir=${phasedir} --cover=${cover} --angle=90 -v

mv pulse* $subjdir/
