#!/bin/sh

#   POSSUM
#
#   Ivana Drobnjak & Mark Jenkinson, FMRIB Analysis Group
#
#   Copyright (C) 2005-2007 University of Oxford
#
#   Part of FSL - FMRIB's Software Library
#   http://www.fmrib.ox.ac.uk/fsl
#   fsl@fmrib.ox.ac.uk
#   
#   Developed at FMRIB (Oxford Centre for Functional Magnetic Resonance
#   Imaging of the Brain), Department of Clinical Neurology, Oxford
#   University, Oxford, UK
#   
#   
#   LICENCE
#   
#   FMRIB Software Library, Release 5.0 (c) 2012, The University of
#   Oxford (the "Software")
#   
#   The Software remains the property of the University of Oxford ("the
#   University").
#   
#   The Software is distributed "AS IS" under this Licence solely for
#   non-commercial use in the hope that it will be useful, but in order
#   that the University as a charitable foundation protects its assets for
#   the benefit of its educational and research purposes, the University
#   makes clear that no condition is made or to be implied, nor is any
#   warranty given or to be implied, as to the accuracy of the Software,
#   or that it will be suitable for any particular purpose or for use
#   under any specific conditions. Furthermore, the University disclaims
#   all responsibility for the use which is made of the Software. It
#   further disclaims any liability for the outcomes arising from using
#   the Software.
#   
#   The Licensee agrees to indemnify the University and hold the
#   University harmless from and against any and all claims, damages and
#   liabilities asserted by third parties (including claims for
#   negligence) which arise directly or indirectly from the use of the
#   Software or the sale of any products based on the Software.
#   
#   No part of the Software may be reproduced, modified, transmitted or
#   transferred in any form or by any means, electronic or mechanical,
#   without the express permission of the University. The permission of
#   the University is not required if the said reproduction, modification,
#   transmission or transference is done without financial return, the
#   conditions of this Licence are imposed upon the receiver of the
#   product, and all original and amended source code is included in any
#   transmitted product. You may be held legally responsible for any
#   copyright infringement that is caused or encouraged by your failure to
#   abide by these terms and conditions.
#   
#   You are not permitted under this Licence to use this Software
#   commercially. Use for which any financial return is received shall be
#   defined as commercial use, and includes (1) integration of all or part
#   of the source code or the Software into a product for sale or license
#   by or on behalf of Licensee to third parties or (2) use of the
#   Software or any derivative of it for research with the final aim of
#   developing software products for sale or license to a third party or
#   (3) use of the Software or any derivative of it for research with the
#   final aim of developing non-software products for sale or license to a
#   third party, or (4) use of the Software to provide any service to an
#   external organisation for which payment is received. If you are
#   interested in using the Software commercially, please contact Isis
#   Innovation Limited ("Isis"), the technology transfer company of the
#   University, to negotiate a licence. Contact details are:
#   innovation@isis.ox.ac.uk quoting reference DE/9564.
export LC_ALL=C



Usage() {
echo "./generate_b0 <structural> <fieldmap> <TEdiff>"
echo ""
echo "Used for generating B0 inhomogeneity image for POSSUM."
echo ""
echo "<structural> is a T1 weighted image, preferably 1x1x1mm voxel size."
echo "<fieldmap> are 2 complex volumes (in the one file) acquired for two different TE's."
echo "<TEdiff> is the difference of those two TE's (default=2.5ms)."
echo "Note that structural and fieldmap need to have the same dimensions and voxel sizes."
echo "Default filename of the output is <fieldmap>_possum."
echo ""
exit 1
}
[ "$1" = "" ] && Usage

struct=`remove_ext $1`
fmap=`remove_ext $2`
TEdiff=$3
if [ "$3" = "" ]; then 
   TEdiff=2.5
fi

echo "b0 inhomogeneity generation ... "

gamma=2.675e+8
fslcomplex -realabs ${fmap} ${fmap}abs_possumtmp 0 1
fslcomplex -realphase ${fmap} ${fmap}phase1_possumtmp 0 0
fslcomplex -realphase ${fmap} ${fmap}phase2_possumtmp 1 1

fslmaths ${fmap}phase1_possumtmp -sub ${fmap}phase2_possumtmp ${fmap}phasediff_possumtmp -odt float

fslcomplex -complexpolar ${fmap}abs_possumtmp ${fmap}phasediff_possumtmp ${fmap}complex_possumtmp 0 0 
fslcomplex -realphase ${fmap}complex_possumtmp ${fmap}phase_possumtmp 0 0

prelude -a ${fmap}abs_possumtmp -p ${fmap}phase_possumtmp -o ${fmap}uphase_possumtmp -v
fslmaths ${fmap}uphase_possumtmp -mul 1000 -div ${TEdiff}  ${fmap}_b0_radps_possumtmp -odt float
fslmaths ${fmap}_b0_radps_possumtmp -div ${gamma} ${fmap}_b0_tesla_possumtmp -odt float

#register b0 (which is now in tesla) to the structural image
bet ${fmap}abs_possumtmp ${fmap}abs_brain_possumtmp -f 0.5 -g 0

flirt -in ${fmap}abs_brain_possumtmp -ref ${struct} -omat ${fmap}_regmatrix_possumtmp.mat  -bins 256 -cost corratio -searchrx -90 90 -searchry -90 90 -searchrz -90 90 -dof 7

flirt -in ${fmap}_b0_tesla_possumtmp -ref ${struct} -out ${fmap}_b0_possumtmp -applyxfm -init ${fmap}_regmatrix_possumtmp.mat -interp trilinear

fslmaths ${fmap}_b0_possumtmp -mul -1 ${fmap}_possum
rm ${fmap}*possumtmp*
