#!/bin/sh

# basil_var
# Variance calculator for BASIL
# Calculates variance for all parameters in all the steps using fabber_var
# M Chappell 1/11/2007 and M Webster
# Analysis Group, FMRIB, University of Oxford

#HISTORY
#13-12-2007 Update to work with new fabber_var (requries mask)

#deal with options
#   Copyright (C) 2007-2012 University of Oxford

#   Part of FSL - FMRIB's Software Library
#   http://www.fmrib.ox.ac.uk/fsl
#   fsl@fmrib.ox.ac.uk
#   
#   Developed at FMRIB (Oxford Centre for Functional Magnetic Resonance
#   Imaging of the Brain), Department of Clinical Neurology, Oxford
#   University, Oxford, UK
#   
#   
#   LICENCE
#   
#   FMRIB Software Library, Release 5.0 (c) 2012, The University of
#   Oxford (the "Software")
#   
#   The Software remains the property of the University of Oxford ("the
#   University").
#   
#   The Software is distributed "AS IS" under this Licence solely for
#   non-commercial use in the hope that it will be useful, but in order
#   that the University as a charitable foundation protects its assets for
#   the benefit of its educational and research purposes, the University
#   makes clear that no condition is made or to be implied, nor is any
#   warranty given or to be implied, as to the accuracy of the Software,
#   or that it will be suitable for any particular purpose or for use
#   under any specific conditions. Furthermore, the University disclaims
#   all responsibility for the use which is made of the Software. It
#   further disclaims any liability for the outcomes arising from using
#   the Software.
#   
#   The Licensee agrees to indemnify the University and hold the
#   University harmless from and against any and all claims, damages and
#   liabilities asserted by third parties (including claims for
#   negligence) which arise directly or indirectly from the use of the
#   Software or the sale of any products based on the Software.
#   
#   No part of the Software may be reproduced, modified, transmitted or
#   transferred in any form or by any means, electronic or mechanical,
#   without the express permission of the University. The permission of
#   the University is not required if the said reproduction, modification,
#   transmission or transference is done without financial return, the
#   conditions of this Licence are imposed upon the receiver of the
#   product, and all original and amended source code is included in any
#   transmitted product. You may be held legally responsible for any
#   copyright infringement that is caused or encouraged by your failure to
#   abide by these terms and conditions.
#   
#   You are not permitted under this Licence to use this Software
#   commercially. Use for which any financial return is received shall be
#   defined as commercial use, and includes (1) integration of all or part
#   of the source code or the Software into a product for sale or license
#   by or on behalf of Licensee to third parties or (2) use of the
#   Software or any derivative of it for research with the final aim of
#   developing software products for sale or license to a third party or
#   (3) use of the Software or any derivative of it for research with the
#   final aim of developing non-software products for sale or license to a
#   third party, or (4) use of the Software to provide any service to an
#   external organisation for which payment is received. If you are
#   interested in using the Software commercially, please contact Isis
#   Innovation Limited ("Isis"), the technology transfer company of the
#   University, to negotiate a licence. Contact details are:
#   innovation@isis.ox.ac.uk quoting reference DE/9564.
export LC_ALL=C


if [ -z $1 ]; then
    echo "Variance calculator for BASIL"
    echo ""
    echo "Usage:"
    echo "-d     : BASIL results directory"
    echo "-m     : mask"
    echo ""
    break
else

#fabber_var=~/cproject/fabber/fabber_var
fabber_var=${FSLDIR}/bin/fabber_var

until [ -z $1 ]; do
    case $1 in
	-d) dirflag=1 datdir=$2;;
	-m) maskflag=1 mask=$2;;
	-c) trashflag=1;;
     esac
    shift
done
echo "BASIL variance calcualtor"
echo "Working in $datdir"

steps=`ls -d $datdir/step[0-9]`

if [ ! -z $trashflag ]; then
    # Remove extra NLLS outputs
    echo "Delting model fit and residual images from NLLS to save space"
    rm $datdir/step?/residuals.nii.gz
    rm $datdir/step?/modelfit.nii.gz
fi

for step in $steps; do
    echo "Calculating variances in $step"
    $fabber_var -d $step -m $mask
    if [ ! -z $trashflag ]; then
	#echo "Deleting z-stat images to save space"
	#rm $step/zstat_*
	echo "Compacting logfile"
	zip $step/logfile $step/logfile
	rm $step/logfile
    fi
done
fi

echo "Done."
