#!/bin/sh


configure_script=${FSLDIR}/config/${FSLMACHTYPE}/configure.sh
if [ -f ${configure_script} ]; then
    . ${configure_script}
fi
# Note, over-ride the settings of the configure_opts as doesn't support --disable-dependency-tracking
configure_opts="--prefix=${FSLDEVDIR}"
if [ `uname` == "Darwin" ]; then
    configure_opts="--prefix=${FSLDEVDIR} --static"
fi

echo "CFLAGS=\"${cflags}\" LDFLAGS=\"${ldflags}\" ./configure ${configure_opts}"
CFLAGS="${cflags}" CPPFLAGS="${cppflags}" LDFLAGS="${ldflags}" ./configure ${configure_opts}
