#!/bin/sh

if [ `uname` = "Darwin" ] ; then
  DYLD_LIBRARY_PATH=${FSLDIR}/bin/fslview.app/Contents/Frameworks
  export DYLD_LIBRARY_PATH
  ${FSLDIR}/bin/atlasquery_bin "$1" "$2" "$3" "$4" "$5" "$6" "$7" "$8" "$9" "$10"
fi
if [ `uname` = "Linux" ] ; then
  LD_LIBRARY_PATH=${FSLDIR}/lib:${LD_LIBRARY_PATH}
  export LD_LIBRARY_PATH
  ${FSLDIR}/bin/atlasquery_bin "$1" "$2" "$3" "$4" "$5" "$6" "$7" "$8" "$9" "$10"
fi
