#!/bin/sh
 
#   Copyright (C) 2004 University of Oxford
#
#   Part of FSL - FMRIB's Software Library
#   http://www.fmrib.ox.ac.uk/fsl
#   fsl@fmrib.ox.ac.uk
#   
#   Developed at FMRIB (Oxford Centre for Functional Magnetic Resonance
#   Imaging of the Brain), Department of Clinical Neurology, Oxford
#   University, Oxford, UK
#   
#   
#   LICENCE
#   
#   FMRIB Software Library, Release 5.0 (c) 2012, The University of
#   Oxford (the "Software")
#   
#   The Software remains the property of the University of Oxford ("the
#   University").
#   
#   The Software is distributed "AS IS" under this Licence solely for
#   non-commercial use in the hope that it will be useful, but in order
#   that the University as a charitable foundation protects its assets for
#   the benefit of its educational and research purposes, the University
#   makes clear that no condition is made or to be implied, nor is any
#   warranty given or to be implied, as to the accuracy of the Software,
#   or that it will be suitable for any particular purpose or for use
#   under any specific conditions. Furthermore, the University disclaims
#   all responsibility for the use which is made of the Software. It
#   further disclaims any liability for the outcomes arising from using
#   the Software.
#   
#   The Licensee agrees to indemnify the University and hold the
#   University harmless from and against any and all claims, damages and
#   liabilities asserted by third parties (including claims for
#   negligence) which arise directly or indirectly from the use of the
#   Software or the sale of any products based on the Software.
#   
#   No part of the Software may be reproduced, modified, transmitted or
#   transferred in any form or by any means, electronic or mechanical,
#   without the express permission of the University. The permission of
#   the University is not required if the said reproduction, modification,
#   transmission or transference is done without financial return, the
#   conditions of this Licence are imposed upon the receiver of the
#   product, and all original and amended source code is included in any
#   transmitted product. You may be held legally responsible for any
#   copyright infringement that is caused or encouraged by your failure to
#   abide by these terms and conditions.
#   
#   You are not permitted under this Licence to use this Software
#   commercially. Use for which any financial return is received shall be
#   defined as commercial use, and includes (1) integration of all or part
#   of the source code or the Software into a product for sale or license
#   by or on behalf of Licensee to third parties or (2) use of the
#   Software or any derivative of it for research with the final aim of
#   developing software products for sale or license to a third party or
#   (3) use of the Software or any derivative of it for research with the
#   final aim of developing non-software products for sale or license to a
#   third party, or (4) use of the Software to provide any service to an
#   external organisation for which payment is received. If you are
#   interested in using the Software commercially, please contact Isis
#   Innovation Limited ("Isis"), the technology transfer company of the
#   University, to negotiate a licence. Contact details are:
#   innovation@isis.ox.ac.uk quoting reference DE/9564.
export LC_ALL=C

usage()
{
echo "Usage : $0 <big4D dataset> <avg file>"
echo ""
    echo "       This script assumes that there are 3"
    echo "       separate averages of 0, 29, 0, 31, 0, 0, 0 b-values"
    echo "       You need to also run Make_bvecs in matlab"
    echo "       <artefactfile> is optional"
    exit 1
}
 
[ $# -lt 2 ] && usage
data=`remove_ext ${1}`;


if [ `imtest $data` -eq 0 ];then
    echo "Cannot find image called $1";
    exit
fi
avgfile=$2;
if [ ! -e $avgfile ];then
    echo " Cannot find $2"
    exit
fi

numlines=`cat $avgfile |grep -v '^ *$'|wc -l`;
numavgs=`expr $numlines - 1`;
scans_per_avg=`cat $avgfile |sed 's/, *$/ /g'|sed 's/[^,]/ /g'|sed -n '1p'|wc -w`;
scans_per_avg=`expr $scans_per_avg + 1`
b0_numbers=`cat $avgfile |grep -v '^ *$' |sed -n "${numlines}p"`;


ab0=`echo $b0_numbers |awk '{print \$1}'`
eddy_correct ${1} ${$}${1}_b0_correct $ab0
total_vols=`fslval $1 dim4`;
vols_per_avg=`echo "10k $total_vols $numavgs / p"|dc -`;
fslroi ${1} data 0 ${vols_per_avg};
fslmaths data -mul 0 data;


avg=1;scan=1;
while [ ${avg} -le ${numavgs} ]; do
    scan=1
#echo ${scan} ${scans_per_avg}
    while [ ${scan} -le ${scans_per_avg} ]; do

	tmp=`cat $avgfile |sed -n "${avg}p"|awk -F , "{ print \\$$scan }"`;

	echo $avg $scan $tmp $vols_per_avg
	
	fslroi ${$}${1}_b0_correct ${$}avg_${avg}_scan_${scan} $tmp;
    	scan=`expr $scan + 1`;
    done
    fslmerge -t ${$}avg_${avg}_all `imglob ${$}avg_${avg}_scan_*`
    fslmaths data  -add ${$}avg_${avg}_all data;
    avg=`expr $avg + 1`;
    
done
fslmaths data -div ${numavgs} data;
rm ${$}*







