#!/bin/sh

#   Copyright (C) 2004 University of Oxford
#
#   Part of FSL - FMRIB's Software Library
#   http://www.fmrib.ox.ac.uk/fsl
#   fsl@fmrib.ox.ac.uk
#   
#   Developed at FMRIB (Oxford Centre for Functional Magnetic Resonance
#   Imaging of the Brain), Department of Clinical Neurology, Oxford
#   University, Oxford, UK
#   
#   
#   LICENCE
#   
#   FMRIB Software Library, Release 5.0 (c) 2012, The University of
#   Oxford (the "Software")
#   
#   The Software remains the property of the University of Oxford ("the
#   University").
#   
#   The Software is distributed "AS IS" under this Licence solely for
#   non-commercial use in the hope that it will be useful, but in order
#   that the University as a charitable foundation protects its assets for
#   the benefit of its educational and research purposes, the University
#   makes clear that no condition is made or to be implied, nor is any
#   warranty given or to be implied, as to the accuracy of the Software,
#   or that it will be suitable for any particular purpose or for use
#   under any specific conditions. Furthermore, the University disclaims
#   all responsibility for the use which is made of the Software. It
#   further disclaims any liability for the outcomes arising from using
#   the Software.
#   
#   The Licensee agrees to indemnify the University and hold the
#   University harmless from and against any and all claims, damages and
#   liabilities asserted by third parties (including claims for
#   negligence) which arise directly or indirectly from the use of the
#   Software or the sale of any products based on the Software.
#   
#   No part of the Software may be reproduced, modified, transmitted or
#   transferred in any form or by any means, electronic or mechanical,
#   without the express permission of the University. The permission of
#   the University is not required if the said reproduction, modification,
#   transmission or transference is done without financial return, the
#   conditions of this Licence are imposed upon the receiver of the
#   product, and all original and amended source code is included in any
#   transmitted product. You may be held legally responsible for any
#   copyright infringement that is caused or encouraged by your failure to
#   abide by these terms and conditions.
#   
#   You are not permitted under this Licence to use this Software
#   commercially. Use for which any financial return is received shall be
#   defined as commercial use, and includes (1) integration of all or part
#   of the source code or the Software into a product for sale or license
#   by or on behalf of Licensee to third parties or (2) use of the
#   Software or any derivative of it for research with the final aim of
#   developing software products for sale or license to a third party or
#   (3) use of the Software or any derivative of it for research with the
#   final aim of developing non-software products for sale or license to a
#   third party, or (4) use of the Software to provide any service to an
#   external organisation for which payment is received. If you are
#   interested in using the Software commercially, please contact Isis
#   Innovation Limited ("Isis"), the technology transfer company of the
#   University, to negotiate a licence. Contact details are:
#   innovation@isis.ox.ac.uk quoting reference DE/9564.
export LC_ALL=C

usage()
{
    echo "Usage :ocmr_preproc <number of slices per volume>"
    echo ""
    exit 1
}
 
[ $# -lt 1 ] && usage

nep=`echo *ep2d_* |wc -w`
nlp=`echo *lp2d_* |wc -w`

if [ $nep -gt 1 ];then 
    a1=`imglob images_?_*ep2d_*`
    a2=`imglob images_??_*ep2d_*`
    a3=`imglob images_???_*ep2d_*`
    
    fslmerge -t big4D $a1 $a2 $a3

elif [ $nlp -gt 1 ];then 
    a1=`imglob images_?_*lp2d_*`
    a2=`imglob images_??_*lp2d_*`
    a3=`imglob images_???_*lp2d_*`
    fslmerge -t big4D $a1 $a2 $a3

fi

#nslices=${1}
#zsize=`fslval big4D dim3`
#tsize=`fslval big4D dim4`
#tpts=`echo "10k $zsize $nslices /p "|dc -` 
#afterdot=`echo $tpts | awk -F . '{print \$2}'`
#foo=`echo $afterdot|grep  [123456798]`
#if [ ! "$foo" = "" ]; then
#    echo "wrong number of slices somewhere - exiting"
#    exit 1
#fi
#tpts=`echo "$tpts \* $tsize" |bc"'
#xsize=`fslval big4D dim1`
#ysize=`fslval big4D dim2`
#xvoxsize=`fslval big4D pixdim1`
#yvoxsize=`fslval big4D pixdim2`
#zvoxsize=`fslval big4D pixdim3`
#datatype=`fslval big4D datatype`


#fslcreatehd $xsize $ysize $nslices $tpts $xvoxsize $yvoxsize $zvoxsize 0 0 0 0# $datatype big4D 




